app/models/product.py
from app import db


class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, default=db.func.current_timestamp(),
                           onupdate=db.func.current_timestamp())

    def __str__(self):
        return self.name


class Product(db.Model):
    __tablename__ = 'product'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    color = db.Column(db.String(100))
    size = db.Column(db.Float())
    barcode = db.Column(db.String(100), unique=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    description = db.Column(db.String(100))
    image = db.Column(db.Unicode(128))
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())
    category = db.relationship("Category", foreign_keys=[category_id])

    def __str__(self):
        return self.name

app/store/category/forms.py
from flask_wtf import FlaskForm
from flask_babel import _, lazy_gettext as _l
from wtforms.fields import StringField, SubmitField
from wtforms import ValidationError
from wtforms.validators import InputRequired, Length
from app.models import Category


class CategoryForm(FlaskForm):
    name = StringField(_l('Category name'), validators=[InputRequired(), Length(1, 100)])
    submit = SubmitField(_l('Add category'))

    def validate_name(form, field):
        if Category.query.filter_by(name=field.data).first():
            raise ValidationError(_('Category name already registered!'))

app/store/product/forms.py
from flask_wtf import FlaskForm
from flask_babel import _, lazy_gettext as _l
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields import StringField, SubmitField, FileField, FloatField
from wtforms import ValidationError, TextAreaField
from wtforms.validators import InputRequired, Length, required
from app.models import Product, Category


class ProductForm(FlaskForm):
    name = StringField(_l('Product name'), validators=[InputRequired(), Length(1, 100)])
    color = StringField(_l('Color'), validators=[Length(0, 100)])
    size = FloatField(_l('Size'), validators=[InputRequired()])
    barcode = StringField(_l('Barcode'), validators=[Length(1, 50)])
    image = FileField(_l('Course Image'))
    description = TextAreaField(_l('Description', validators=[Length(0, 100)]))
    category = QuerySelectField(_l('Category'), validators=[required('validators ')],
                                query_factory=lambda: Category.query.all())
    submit = SubmitField(_l('Add product'))

    def validate_name(form, field):
        if Product.query.filter_by(name=field.data).first():
            raise ValidationError(_('Product name already registered!'))

app/store/category/__init__.py
from flask import Blueprint

category = Blueprint('category', __name__)

from app.store.category import views

app/store/category/views.py
from flask import render_template, url_for, flash
from werkzeug.exceptions import abort
from werkzeug.utils import redirect
from flask_babel import _

from app import db
from app.models import Category
from app.store.category import category as bp
from app.store.category.forms import CategoryForm


@bp.route('/')
@bp.route('/categories')
def categories():
    categories = Category.query.all()
    return render_template('store/category/categories.html', categories=categories)


@bp.route('/add-category', methods=['GET', 'POST'])
def add_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        try:
            db.session.commit()
        except Exception as e:
            flash(str(e), 'error')
            return redirect(url_for('category.add_category'))
        flash(_('Successfully added new category'), 'success')
        return redirect(url_for('category.categories'))
    return render_template('store/category/manipulate-category.html', form=form)


@bp.route('/delete_category/<int:category_id>')
def delete_category(category_id):
    """Delete a user's account."""
    category = Category.query.filter_by(id=category_id).first()
    if category is None:
        abort(404)
    db.session.delete(category)
    try:
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        flash(str(e), 'error')
        return redirect(url_for('category.categories', category_id=category_id))
    flash(_('successfully deleted %(category_name)s category', category_name=category.name), 'success')
    return redirect(url_for('category.categories'))


@bp.route('/edit_category/<int:category_id>', methods=['GET', 'POST'])
def edit_category(category_id):
    """Edit a category's information."""
    category = Category.query.filter_by(id=category_id).first()
    if category is None:
        abort(404)

    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
        flash(_('Successfully edit category'), 'success')
        return redirect(url_for('category.categories'))
    return render_template('store/category/manipulate-category.html', category=category, form=form)

app/store/product/__init__.py
from flask import Blueprint

product = Blueprint('product', __name__)

from app.store.product import views

app/store/product/views.py
from flask import render_template, url_for, flash, request
from werkzeug.exceptions import abort
from werkzeug.utils import redirect
from flask_babel import _

from app import db, photos
from app.models import Category, Product
from app.store.product import product as bp
from app.store.product.forms import ProductForm


@bp.route('/')
@bp.route('/products')
def products():
    products = Product.query.all()
    return render_template('store/product/products.html', products=products)


@bp.route('/add-product', methods=['GET', 'POST'])
def add_product():
    form = ProductForm()
    if form.validate_on_submit():
        product_name = form.name.data
        category = Category.query.filter_by(name=str(form.category.data)).first()
        try:
            filename = photos.save(request.files['image'], name="product/" + str(product_name) + "_product.")
        except Exception as e:
            flash(_('Please input correct image format'), 'error')
            return redirect(url_for('operator.add_course'))
        product = Product(
            name=product_name,
            category_id=category.id,
            description=form.description.data,
            color=form.color.data,
            image=filename,
            size=form.size.data,
            barcode=form.barcode.data,
        )
        db.session.add(product)
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash(str(e), 'error')
            return redirect(url_for('product.add_product'))
        flash(_('Successfully added new product'), 'success')
        return redirect(url_for('product.products'))
    return render_template('store/product/manipulate-product.html', form=form)


@bp.route('/delete_product/<int:product_id>')
def delete_product(product_id):
    """Delete a user's account."""
    product = Product.query.filter_by(id=product_id).first()
    if product is None:
        abort(404)
    db.session.delete(product)
    try:
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        flash(str(e), 'error')
        return redirect(url_for('product.products'))
    flash(_('successfully deleted %(product_name)s product', product_name=product.name), 'success')
    return redirect(url_for('product.products'))


@bp.route('/edit_product/<int:product_id>', methods=['GET', 'POST'])
def edit_product(product_id):
    """Edit a product's information."""
    product = Product.query.filter_by(id=product_id).first()
    if product is None:
        abort(404)

    form = ProductForm(obj=product)
    if form.validate_on_submit():
        category = Category.query.filter_by(name=str(form.category.data)).first()

        product_name = form.name.data,
        product.name = product_name,
        product.color = form.color.data,
        product.size = form.size.data,
        product.barcode = form.barcode.data,
        product.category_id = category.id,
        product.description = form.description.data

        try:
            filename = photos.save(request.files['image'], name="product/" + str(product_name) + "_product.")
            product.image = filename
        except Exception as e:
            flash(_('Please input correct image format'), 'error')
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash(_('Successfully edit product'), 'success')
            return redirect(url_for('product.edit_product', product_id=product_id))
        flash(_('Successfully edit product'), 'success')
        return redirect(url_for('product.products'))
    return render_template('store/product/manipulate-product.html', product=product, form=form)

app/templates/store/product/manipulate-product.html
{% extends "layouts/base-template.html" %}
{% import 'macros/form_macros.html' as f %}

{% block scripts %}
{% endblock %}

{% block content %}

<style>
  button {
    width: 75px;
    height: 35px;
    margin-top: -20px;
  }
</style>

<div id="mainContent">
  <div class="row gap-20 masonry pos-r">
    <div class="masonry-sizer col-md-6"></div>
    <div class="masonry-item col-md-6">
      <div class="bgc-white p-20 bd">
        {% if course %}
          <h2 class="c-grey-900">{{ _('Edit Product') }}</h2>
        {% else %}
          <h2 class="c-grey-900">{{ _('Add new Product') }}</h2>
        {% endif %}
        {% set flashes = {
        'error': get_flashed_messages(category_filter=['form-error']),
        'warning': get_flashed_messages(category_filter=['form-check-email']),
        'info': get_flashed_messages(category_filter=['form-info']),
        'success': get_flashed_messages(category_filter=['form-success'])
        } %}
        <div class="mT-30">
          {{ f.begin_form(form, flashes) }}
	          {% if product %}
			        {{ f.render_form_field(form.name, value=product.name) }}
		          {{ f.render_form_field(form.category, value=product.category) }}
		          {{ f.render_form_field(form.color, value=product.color) }}
			        {{ f.render_form_field(form.size, value=product.size) }}
			        {{ f.render_form_field(form.barcode, value=product.barcode) }}
			        {{ f.render_form_field(form.image, value=product.image) }}
			        {{ f.render_form_field(form.description, value=product.description) }}
	          {% else %}
			        {{ f.render_form_field(form.name) }}
		          {{ f.render_form_field(form.category) }}
		          {{ f.render_form_field(form.color) }}
			        {{ f.render_form_field(form.size) }}
			        {{ f.render_form_field(form.barcode) }}
			        {{ f.render_form_field(form.image) }}
			        {{ f.render_form_field(form.description) }}
		        {% endif %}
		        {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
	          {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
	          {{ f.form_message(flashes['info'], header='Information', class='info') }}
	          {{ f.form_message(flashes['success'], header='Success!', class='success') }}
	          <br>
	          {#{{ f.render_form_field(form.submit) }}#}
	          <button type="submit" class="btn btn-primary d-flex justify-content-center d-md-table mx-auto">Submit</button>
          {{ f.end_form() }}
        </div>
      </div>
      {# Implement CSRF protection for site #}
      {% if csrf_token()|safe %}
      <div style="visibility: hidden; display: none">
        <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}">
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/store/product/products.html
{% extends "layouts/base-template.html" %}
{% block content %}
<style>
	.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
		background-color: #C0D890;
	}
	tfoot input {
		width: 100%;
		padding: 3px;
		box-sizing: border-box;
	}
</style>
<div class="">
	<div class="clearfix"></div>
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>{{ _('Products') }}</h2>
					<div class="d-flex justify-content-end">
						<div class="p-2" style="margin-top: 10px;">
						</div>
						<div class="p-2" style="margin-top: 10px;">
							<a href="{{ url_for('product.add_product') }}" class="btn btn-primary d-flex justify-content-center d-md-table mx-auto">{{ _('Add new Product') }}</a>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<table id="example" class="table table-striped table-bordered dt-responsive nowrap table table-striped table-hover display" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>{{ _('Name') }}</th>
								<th>{{ _('Category') }}</th>
								<th>{{ _('Color') }}</th>
								<th>{{ _('Size') }}</th>
								<th>{{ _('Barcode') }}</th>
								<th>{{ _('Image') }}</th>
								<th>{{ _('Description') }}</th>
								<th>{{ _('Created at') }}</th>
								<th>{{ _('Update at') }}</th>
								<th>{{ _('Action') }}</th>
							</tr>
						</thead>
						<tbody>
						{% for data in products %}
							<tr>
								<td>{{ data.name }}</td>
								<td>{{ data.category }}</td>
								<td>{{ data.color }}</td>
								<td>{{ data.size }}</td>
								<td>{{ data.barcode }}</td>
								<td>
									{% if data.image %}
										<img class="card-img-top" src="{{ url_for('static', filename='images/app/'+data['image']) }}" alt="{{data.image}}" style="width: 120px; height: 120px;">
									{% else %}
									{% endif %}
								</td>
								<td>{{ data.description }}</td>
								<td>{{ data.created_at }}</td>
								<td>{{ data.updated_at }}</td>
								<td>
									<a href="{{ url_for('product.edit_product', product_id=data.id) }}"><button class="btn btn-info">Edit</button></a>
									<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#ConfirmDeleteModal{{ data.id }}">{{ _('Delete') }}</button>
								</td>
							</tr>
							<!-- Modal -->
							<div class="modal fade" id="ConfirmDeleteModal{{ data.id }}" tabindex="-1" role="dialog" aria-labelledby="ConfirmDeleteModalLabel" aria-hidden="true">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="ConfirmDeleteModalLabel">Action</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											{{ _('Are you sure to delete this product..?') }}
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('No') }}</button>
											<a href="{{ url_for('product.delete_product', product_id=data.id) }}"><button type="button" class="btn btn-danger">{{ _('Yes') }}</button></a>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
						</tbody>
							<tfoot>
								<tr>
									<th>{{ _('Name') }}</th>
									<th>{{ _('Category') }}</th>
									<th>{{ _('Color') }}</th>
									<th>{{ _('Size') }}</th>
									<th>{{ _('Barcode') }}</th>
									<th>{{ _('Image') }}</th>
									<th>{{ _('Description') }}</th>
									<th>{{ _('Created at') }}</th>
									<th>{{ _('Update at') }}</th>
									<th>{{ _('Action') }}</th>
								</tr>
		        </tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}